const mongoose = require('mongoose');
const Product = require('./models/Product');
const Category = require('./models/Category');
require('dotenv').config();

mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/gk-fashion')
  .then(async () => {
    console.log('✅ Connected to MongoDB');
    
    // Find or create categories
    let women = await Category.findOne({ name: /^women$/i });
    if (!women) women = await Category.create({ name: 'Women', description: 'Women\'s Fashion', isActive: true });
    
    let men = await Category.findOne({ name: /^men$/i });
    if (!men) men = await Category.create({ name: 'Men', description: 'Men\'s Fashion', isActive: true });
    
    console.log('✅ Categories ready');
    
    // Clear existing products
    await Product.deleteMany({});
    console.log('🗑️  Cleared existing products');
    
    // Women's products with Indian pricing (₹)
    const womenProducts = [
      { name: "Elegant Floral Anarkali Kurta", description: "Beautiful floral printed Anarkali kurta with intricate embroidery. Perfect for festive occasions.", price: 1299, comparePrice: 2499, category: women._id, subcategory: "Ethnic Wear", brand: "Fabindia", images: [{ public_id: "w1", url: "https://images.unsplash.com/photo-1583391733956-6c78276477e5?w=500" }], variants: [{ size: "S", color: "Pink", sku: "WK001-S", stock: 25 }, { size: "M", color: "Pink", sku: "WK001-M", stock: 30 }, { size: "L", color: "Pink", sku: "WK001-L", stock: 25 }], features: ["Premium cotton", "Embroidery", "Comfortable"], specifications: { material: "Cotton Blend", care: "Machine wash" }, tags: ["kurta", "ethnic", "festive"], ratings: { average: 4.7, count: 342 }, isFeatured: true },
      { name: "Designer Banarasi Silk Saree", description: "Exquisite Banarasi silk saree with traditional zari work. Perfect for weddings.", price: 4999, comparePrice: 8999, category: women._id, subcategory: "Sarees", brand: "Kanchipuram Silks", images: [{ public_id: "w2", url: "https://images.unsplash.com/photo-1564257577-d18b2b6d2b6e?w=500" }], variants: [{ size: "S", color: "White", sku: "WB001-S", stock: 12 }, { size: "M", color: "White", sku: "WB001-M", stock: 15 }], features: ["Silk", "Elegant"], specifications: { material: "Silk", care: "Dry clean" }, tags: ["blouse", "silk"], ratings: { average: 4.8, count: 124 }, isFeatured: true },
      { name: "Stylish Denim Jeans", description: "High-quality stretchable denim jeans with perfect fit", price: 899, comparePrice: 1499, category: women._id, subcategory: "Bottoms", brand: "Denim Co", images: [{ public_id: "w3", url: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500" }], variants: [{ size: "26", color: "Blue", sku: "WJ001-26", stock: 20 }, { size: "28", color: "Blue", sku: "WJ001-28", stock: 25 }], features: ["High waist", "Stretch"], specifications: { material: "Denim", care: "Machine wash" }, tags: ["jeans", "denim"], ratings: { average: 4.6, count: 156 }, isFeatured: false },
      { name: "Premium Leather Handbag", description: "Elegant genuine leather handbag with multiple compartments", price: 2499, comparePrice: 4999, category: women._id, subcategory: "Bags & Accessories", brand: "Hidesign", images: [{ public_id: "w4", url: "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=500" }], variants: [{ size: "One Size", color: "Brown", sku: "WBG001-BR", stock: 10 }, { size: "One Size", color: "Black", sku: "WBG001-BK", stock: 12 }], features: ["Leather", "Spacious"], specifications: { material: "Leather", care: "Wipe clean" }, tags: ["handbag", "leather"], ratings: { average: 4.9, count: 78 }, isFeatured: true },
      { name: "Comfortable Sports Shoes", description: "Lightweight sports shoes with superior cushioning", price: 1799, comparePrice: 2999, category: women._id, subcategory: "Shoes", brand: "Comfort Walk", images: [{ public_id: "w5", url: "https://images.unsplash.com/photo-1560769629-975ec94e6a86?w=500" }], variants: [{ size: "6", color: "White", sku: "WS001-6", stock: 15 }, { size: "7", color: "White", sku: "WS001-7", stock: 20 }], features: ["Canvas", "Comfortable"], specifications: { material: "Canvas", care: "Spot clean" }, tags: ["sneakers", "casual"], ratings: { average: 4.5, count: 203 }, isFeatured: false },
      { name: "Gold Plated Jewelry Set", description: "Beautiful gold-plated necklace and earring set with intricate design", price: 799, comparePrice: 1499, category: women._id, subcategory: "Jewelry", brand: "Tanishq", images: [{ public_id: "w6", url: "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=500" }], variants: [{ size: "One Size", color: "Gold", sku: "WN001-GD", stock: 25 }], features: ["Gold-plated", "Statement"], specifications: { material: "Brass", care: "Keep dry" }, tags: ["necklace", "jewelry"], ratings: { average: 4.7, count: 92 }, isFeatured: false },
      { name: "Cotton Palazzo Pants", description: "Comfortable cotton palazzo pants with vibrant prints", price: 599, comparePrice: 999, category: women._id, subcategory: "Dresses", brand: "Boho Chic", images: [{ public_id: "w7", url: "https://images.unsplash.com/photo-1572804013309-59a88b7e92f1?w=500" }], variants: [{ size: "S", color: "Multi", sku: "WMD001-S", stock: 10 }, { size: "M", color: "Multi", sku: "WMD001-M", stock: 15 }], features: ["Maxi", "Bohemian"], specifications: { material: "Rayon", care: "Hand wash" }, tags: ["maxi", "bohemian"], ratings: { average: 4.8, count: 67 }, isFeatured: true },
      { name: "Designer Silk Dupatta", description: "Elegant silk dupatta with beautiful embroidery", price: 899, comparePrice: 1599, category: women._id, subcategory: "Accessories", brand: "Silk Elegance", images: [{ public_id: "w8", url: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=500" }], variants: [{ size: "One Size", color: "Blue", sku: "WSC001-BL", stock: 20 }], features: ["Silk", "Designer"], specifications: { material: "Silk", care: "Dry clean" }, tags: ["scarf", "silk"], ratings: { average: 4.6, count: 45 }, isFeatured: false },
      { name: "Leather Ankle Boots", description: "Stylish leather ankle boots with comfortable heel", price: 2199, comparePrice: 3999, category: women._id, subcategory: "Boots", brand: "Boot Boutique", images: [{ public_id: "w9", url: "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500" }], variants: [{ size: "6", color: "Black", sku: "WAB001-6", stock: 12 }, { size: "7", color: "Black", sku: "WAB001-7", stock: 15 }], features: ["Leather", "Comfortable"], specifications: { material: "Leather", care: "Polish" }, tags: ["boots", "leather"], ratings: { average: 4.7, count: 134 }, isFeatured: true },
      { name: "Printed Cotton Kurti", description: "Vibrant printed cotton kurti perfect for daily wear", price: 699, comparePrice: 1199, category: women._id, subcategory: "Bags", brand: "Travel Essentials", images: [{ public_id: "w10", url: "https://images.unsplash.com/photo-1590874103328-eac38a683ce7?w=500" }], variants: [{ size: "One Size", color: "Black", sku: "WCB001-BK", stock: 18 }], features: ["Adjustable", "Lightweight"], specifications: { material: "Synthetic", care: "Wipe clean" }, tags: ["crossbody", "bag"], ratings: { average: 4.5, count: 98 }, isFeatured: false },
      { name: "Woolen Shawl", description: "Soft and warm woolen shawl perfect for winter", price: 1299, comparePrice: 2199, category: women._id, subcategory: "Sweaters", brand: "Cozy Knits", images: [{ public_id: "w11", url: "https://images.unsplash.com/photo-1576566588028-4147f3842f27?w=500" }], variants: [{ size: "S", color: "Beige", sku: "WKS001-S", stock: 15 }, { size: "M", color: "Beige", sku: "WKS001-M", stock: 20 }], features: ["Soft", "Warm"], specifications: { material: "Acrylic", care: "Hand wash" }, tags: ["sweater", "knit"], ratings: { average: 4.8, count: 112 }, isFeatured: false },
      { name: "Designer Sunglasses", description: "Premium UV protection sunglasses with stylish design", price: 1499, comparePrice: 2999, category: women._id, subcategory: "Sunglasses", brand: "Vision Style", images: [{ public_id: "w12", url: "https://images.unsplash.com/photo-1511499767150-a48a237f0083?w=500" }], variants: [{ size: "One Size", color: "Gold", sku: "WSG001-GD", stock: 20 }], features: ["UV protection", "Polarized"], specifications: { material: "Metal", care: "Clean with cloth" }, tags: ["sunglasses", "aviator"], ratings: { average: 4.9, count: 87 }, isFeatured: true }
    ];
    
    // Men's products with Indian pricing (₹)
    const menProducts = [
      { name: "Premium Cotton Formal Shirt", description: "High-quality cotton formal shirt perfect for office and business meetings", price: 999, comparePrice: 1799, category: men._id, subcategory: "Formal Wear", brand: "Van Heusen", images: [{ public_id: "m1", url: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=500" }], variants: [{ size: "M", color: "White", sku: "MS001-M", stock: 20 }, { size: "L", color: "White", sku: "MS001-L", stock: 25 }], features: ["Wrinkle-resistant", "Cotton"], specifications: { material: "Cotton", care: "Machine wash" }, tags: ["shirt", "formal"], ratings: { average: 4.7, count: 145 }, isFeatured: true },
      { name: "Denim Jeans - Slim Fit", description: "Premium quality denim jeans with perfect slim fit", price: 1299, comparePrice: 2199, category: men._id, subcategory: "Jeans", brand: "Denim Pro", images: [{ public_id: "m2", url: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=500" }], variants: [{ size: "30", color: "Blue", sku: "MJ001-30", stock: 20 }, { size: "32", color: "Blue", sku: "MJ001-32", stock: 25 }], features: ["Slim fit", "Stretch"], specifications: { material: "Denim", care: "Machine wash" }, tags: ["jeans", "denim"], ratings: { average: 4.6, count: 198 }, isFeatured: true },
      { name: "Genuine Leather Jacket", description: "Premium genuine leather jacket with classic design. Perfect for winter.", price: 5999, comparePrice: 9999, category: men._id, subcategory: "Winter Wear", brand: "Woodland", images: [{ public_id: "m3", url: "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500" }], variants: [{ size: "M", color: "Black", sku: "MLJ001-M", stock: 10 }, { size: "L", color: "Black", sku: "MLJ001-L", stock: 12 }], features: ["Genuine leather", "Classic"], specifications: { material: "Leather", care: "Professional care" }, tags: ["jacket", "leather"], ratings: { average: 4.9, count: 76 }, isFeatured: true },
      { name: "Sports Running Shoes", description: "High-performance running shoes with advanced cushioning technology", price: 2499, comparePrice: 3999, category: men._id, subcategory: "Footwear", brand: "Adidas", images: [{ public_id: "m4", url: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500" }], variants: [{ size: "9", color: "Black", sku: "MRS001-9", stock: 18 }, { size: "10", color: "Black", sku: "MRS001-10", stock: 22 }], features: ["Cushioning", "Breathable"], specifications: { material: "Mesh", care: "Wipe clean" }, tags: ["running", "athletic"], ratings: { average: 4.8, count: 234 }, isFeatured: true },
      { name: "Casual Canvas Sneakers", description: "Comfortable canvas sneakers perfect for daily wear", price: 1499, comparePrice: 2499, category: men._id, subcategory: "Footwear", brand: "Puma", images: [{ public_id: "m5", url: "https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=500" }], variants: [{ size: "9", color: "White", sku: "MCS001-9", stock: 20 }, { size: "10", color: "White", sku: "MCS001-10", stock: 25 }], features: ["Canvas", "Comfortable"], specifications: { material: "Canvas", care: "Spot clean" }, tags: ["sneakers", "casual"], ratings: { average: 4.5, count: 167 }, isFeatured: false },
      { name: "Premium Leather Watch", description: "Elegant leather strap watch with precision movement", price: 3999, comparePrice: 6999, category: men._id, subcategory: "Accessories", brand: "Titan", images: [{ public_id: "m6", url: "https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=500" }], variants: [{ size: "One Size", color: "Brown", sku: "MLW001-BR", stock: 15 }], features: ["Leather strap", "Precision"], specifications: { material: "Steel", care: "Keep dry" }, tags: ["watch", "leather"], ratings: { average: 4.8, count: 92 }, isFeatured: true },
      { name: "Cotton Polo T-Shirt", description: "Comfortable cotton polo t-shirt perfect for casual wear", price: 799, comparePrice: 1299, category: men._id, subcategory: "Casual Wear", brand: "Allen Solly", images: [{ public_id: "m7", url: "https://images.unsplash.com/photo-1586790170083-2f9ceadc732d?w=500" }], variants: [{ size: "M", color: "Navy", sku: "MPS001-M", stock: 22 }, { size: "L", color: "Navy", sku: "MPS001-L", stock: 25 }], features: ["Cotton", "Comfortable"], specifications: { material: "Cotton", care: "Machine wash" }, tags: ["polo", "casual"], ratings: { average: 4.6, count: 143 }, isFeatured: false },
      { name: "Genuine Leather Belt", description: "Premium quality genuine leather belt with classic buckle", price: 699, comparePrice: 1199, category: men._id, subcategory: "Belts", brand: "Belt Masters", images: [{ public_id: "m8", url: "https://images.unsplash.com/photo-1624222247344-550fb60583aa?w=500" }], variants: [{ size: "32", color: "Black", sku: "MLB001-32", stock: 20 }], features: ["Genuine leather", "Classic"], specifications: { material: "Leather", care: "Polish" }, tags: ["belt", "leather"], ratings: { average: 4.7, count: 118 }, isFeatured: false },
      { name: "Formal Oxford Shoes", description: "Classic oxford shoes in premium leather. Perfect for office and weddings.", price: 2799, comparePrice: 4499, category: men._id, subcategory: "Footwear", brand: "Clarks", images: [{ public_id: "m9", url: "https://images.unsplash.com/photo-1533867617858-e7b97e060509?w=500" }], variants: [{ size: "9", color: "Black", sku: "MOS001-9", stock: 15 }], features: ["Premium leather", "Classic"], specifications: { material: "Leather", care: "Polish" }, tags: ["oxford", "formal"], ratings: { average: 4.8, count: 95 }, isFeatured: false },
      { name: "Aviator Sunglasses", description: "Premium aviator sunglasses with UV protection", price: 1999, comparePrice: 3499, category: men._id, subcategory: "Sunglasses", brand: "Vision Pro", images: [{ public_id: "m10", url: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=500" }], variants: [{ size: "One Size", color: "Gold", sku: "MSG001-GD", stock: 18 }], features: ["UV protection", "Polarized"], specifications: { material: "Metal", care: "Clean with cloth" }, tags: ["sunglasses", "aviator"], ratings: { average: 4.9, count: 102 }, isFeatured: true },
      { name: "Formal Wool Blazer", description: "Sophisticated wool blend blazer for professional occasions", price: 3999, comparePrice: 5999, category: men._id, subcategory: "Blazers", brand: "Executive Style", images: [{ public_id: "m11", url: "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500" }], variants: [{ size: "M", color: "Navy", sku: "MBZ001-M", stock: 10 }], features: ["Wool blend", "Professional"], specifications: { material: "Wool", care: "Dry clean" }, tags: ["blazer", "formal"], ratings: { average: 4.8, count: 73 }, isFeatured: true },
      { name: "Smart Fitness Watch", description: "Advanced fitness tracking watch with heart rate monitor and GPS", price: 4999, comparePrice: 7999, category: men._id, subcategory: "Smart Watches", brand: "Tech Fitness", images: [{ public_id: "m12", url: "https://images.unsplash.com/photo-1579586337278-3befd40fd17a?w=500" }], variants: [{ size: "One Size", color: "Black", sku: "MSW001-BK", stock: 20 }], features: ["Heart rate", "GPS"], specifications: { material: "Aluminum", care: "Wipe clean" }, tags: ["smartwatch", "fitness"], ratings: { average: 4.9, count: 156 }, isFeatured: true }
    ];
    
    await Product.insertMany([...womenProducts, ...menProducts]);
    console.log(`✅ Added ${womenProducts.length} women's products`);
    console.log(`✅ Added ${menProducts.length} men's products`);
    console.log('\n🎉 Database seeded successfully!');
    
    process.exit(0);
  })
  .catch(err => {
    console.error('❌ Error:', err);
    process.exit(1);
  });
